Map<int, String> pos_to_avail = {
  0: "Sunday,morning",
  1: "Sunday,afternoon",
  2: "Sunday,evening",
  3: "Monday,morning",
  4: "Monday,afternoon",
  5: "Monday,evening",
  6: "Tuesday,morning",
  7: "Tuesday,afternoon",
  8: "Tuesday,evening",
  9: "Wednesday,morning",
  10: "Wednesday,afternoon",
  11: "Wednesday,evening",
  12: "Thursday,morning",
  13: "Thursday,afternoon",
  14: "Thursday,evening",
  15: "Friday,morning",
  16: "Friday,afternoon",
  17: "Friday,evening",
  18: "Saturday,morning",
  19: "Saturday,afternoon",
  20: "Saturday,evening",
};