List<String> specialization_list = [
    "Pianist",
    "Organist",
    "Guitarist",
    "Violinist",
    "Cellist",
    "Trumpeter",
    "Flautist",
    "Clarinetist",
    "Oboist",
    "Saxophonist",
    "Bassoonist",
    "French Horn",
    "Horn",
    "Tuba",
    "Trombonist",
    "Drummer",
    "Choir",
    "Band"
  ];
