List<String> specialization_list = [
    "Accordion",
    "Alto Sax",
    "Alto",
    "Arranging",
    "Bagpipes",
    "Band",
    "Banjo",
    "Bansuri",
    "Baritone Horn",
    "Baritone Sax",
    "Baritone",
    "Bass (Acoustic)",
    "Bass (Electric)",
    "Bass",
    "Bassoon",
    "Beatboxing",
    "Bells",
    "Bongos",
    "Cajón",
    "Castanets",
    "Celeste",
    "Cello",
    "Cello",
    "Chimes",
    "Choir",
    "Choral Conducting",
    "Clarinet",
    "Clavichord",
    "Composing",
    "Conga",
    "Contralto",
    "Cornet",
    "Counter tenor",
    "Crumhorn",
    "Cymbals",
    "DJ Software",
    "Didgeridoo",
    "Djembe",
    "Dobro",
    "Double Bass",
    "Drum computer",
    "Drums/Drum kit",
    "Duduk",
    "Dulcimer",
    "English Horn",
    "Erhu",
    "Euphonium",
    "Fiddle",
    "Flugelhorn",
    "Flute",
    "French Horn",
    "Glockenspiel",
    "Guitar (Acoustic)",
    "Guitar (Electric)",
    "Guitar (Steel)",
    "Harmonica",
    "Harmonium",
    "Harp",
    "Instrumental Conducting",
    "Keyboard",
    "Kora",
    "Koto",
    "Lute",
    "Lyrics",
    "Mandolin",
    "Marimba",
    "Mezzo-soprano",
    "Oboe",
    "Ocarina",
    "Organ",
    "Percussion",
    "Piano",
    "Piccolo",
    "Sarod",
    "Sax",
    "Shakuhachi"
    "Shamisen",
    "Sitar",
    "Soprano Sax",
    "Soprano",
    "Sound sequencer",
    "Synthesizer",
    "Tabla",
    "Taiko",
    "Tambourine",
    "Tape recorder",
    "Tenor Sax",
    "Tenor",
    "Timpani",
    "Triangle",
    "Trombone",
    "Trumpet",
    "Tuba",
    "Turntables",
    "Ukulele",
    "Vibraphone",
    "Viol",
    "Viola",
    "Violin",
    "Vocals",
    "Xylophone",
];
